apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: v0swxwokv-go 
  janus-idp.io/tekton: v0swxwokv-go
  backstage.io/kubernetes-id: v0swxwokv-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: v0swxwokv-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml